### ISSUE TITLE
Ran local-up.sh with appropriate HOCUS_HOSTNAME and the log appeared

### ISSUE THREAD

**Issue by victorbutler** [hocus-dev/hocus#62]
## 🐛 Bug description

I ran `/ops/bin/local-up.sh` and the message `Above you will find the vm build logs with the errors highlighted` appeared.

```
Above you will find the vm build logs with the errors highlighted
Please report this problem here
���  https://github.com/hocus-dev/hocus/issues/new/choose  ���
We will get you a � to help you as quickly as possible
```

Running this on a PhotonOS 4 VM with virtualization enabled on ESXi 6.7.0 Update 3 (Build 15160138)

I actually don't see any **error** or issue but maybe I'm missing it? The last messages say there was an error and it definitely did not start.

## Environment

- Hocus version (commit hash): main branch, commit ff7bab15bc3c6ea39c482eb5afd14359bee025c8
- PhotonOS 4 (Running on vmware ESXi 6.7.0 Update 3 (Build 15160138) with hardware virtualization passthrough enabled
- Screenshot attached for more info

![VMware ESXi - 2023 9_04_09 AM](https://user-images.githubusercontent.com/1063420/233119210-8a27d11d-67c0-464d-9e1d-f90b2dfc2639.png)

Log attached below

[hocus.log.txt](https://github.com/hocus-dev/hocus/files/11274606/hocus.log.txt)

**Comment by gorbak25** [comment]
@victorbutler Thank you for checking out Hocus :) 
The `local-up.sh` script failed on exporting built microvm images to sparse raw files. We build vm's as docker images and then export them via a loop device. The exporting process is currently somewhat flaky, sometimes our CI fails due to it. We will rework the build process soon so this issue won't occur :)

Please rerun the script and check if the script succeeded. If it still fails then could you please check if loop devices work properly on your VM(try mounting something via a loop device)? If you want we may hop on a call and I will help you debug this :)

**Comment by victorbutler** [comment]
I reran the script twice and here are the logs.

Getting a different output now. The notable similarity is the following line:

```
hocus-local-db-1  | /bin/sh: can't open '/docker-entrypoint-initdb.d/keycloak-setup.sh': Permission denied                                                                 
```

Logs attached below
[hocus2.log.txt](https://github.com/hocus-dev/hocus/files/11297068/hocus2.log.txt)
[hocus3.log.txt](https://github.com/hocus-dev/hocus/files/11297070/hocus3.log.txt)

**Comment by hugodutka** [comment]
Could you run `ops/bin/local-cleanup.sh`, do a fresh clone of the repository, and try again? It looks like some files might have been corrupted during the unsuccessful runs. If it still doesn't work, feel free to schedule a debugging session with me: https://zcal.co/hugodutka/hocus-debugging

**Comment by victorbutler** [comment]
I was able to get it running by running the command with sudo 😬

Thanks and feel free to close this issue if you see fit.
